# Generated by Django 5.1 on 2024-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FLIGHTDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=100)),
                ('depreture_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('deprature_time', models.TimeField()),
                ('arival_time', models.TimeField()),
                ('price', models.PositiveBigIntegerField()),
                ('economy', models.PositiveIntegerField(default=200)),
                ('business', models.PositiveIntegerField(default=30)),
                ('fast_class', models.PositiveIntegerField(default=30)),
                ('color', models.CharField(default='blue', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=10)),
            ],
        ),
    ]
