# Generated by Django 5.1 on 2024-10-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLIGHTDATES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightdate', models.DateField()),
                ('business', models.IntegerField()),
                ('economic', models.IntegerField()),
                ('first_class', models.IntegerField()),
                ('flight_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking_app.flightdetails')),
            ],
        ),
    ]
