# Generated by Django 5.1 on 2024-10-10 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking_app', '0003_flightbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FLIGHTTICKETS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passanger_name', models.CharField(max_length=100)),
                ('passanger_age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('sheet_number', models.CharField(max_length=20)),
                ('journy_data', models.DateField()),
                ('class_of_service', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking_app.flightbooking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking_app.flightdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
