# Generated by Django 5.1 on 2024-10-11 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking_app', '0004_flighttickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttickets',
            name='journy_data',
        ),
        migrations.AddField(
            model_name='flighttickets',
            name='journy_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flight_booking_app.flightdates'),
            preserve_default=False,
        ),
    ]
